name: Deploy Strapi

on:
  push: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Package application
      run: |
        tar -czvf strapi-project.tar.gz strapi-project
        
    - name: Upload to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "strapi-project.tar.gz"
        target: "/home/ubuntu/"


    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

   

    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo apt update
          sudo apt install -y tar unzip
          cd /home/ubuntu
          tar -xzvf strapi-project.tar.gz
          cd strapi-project
          npm install
          yarn install
          yarn build
          pm2 restart all || pm2 start npm --name "strapi" -- run start
