name: Terraform Deployment

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: .

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      working-directory: .
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Capture instance IP
      id: get_ip
      run: |
        instance_ip=$(terraform output instance_ip)
        echo "Captured IP: $instance_ip"
      working-directory: .

